import PageTitle from "@/components/PageTitle";
import RelatedBlogs from "@/components/RelatedBlogs";
import { ENDPOINTS } from "@/lib/endpoints";
import { BlogType } from "@/lib/types";
import { getData } from "@/lib/utils";
import type { Metadata } from "next";

export const revalidate = 86400;

interface BlogDetailPageProps {
  params: {
    blogId: string;
  };
}

export async function generateMetadata({
  params,
}: BlogDetailPageProps): Promise<Metadata> {
  const blog = await getData<{ title: string }>(
    `${ENDPOINTS.BLOGS}/${params.blogId}`
  );

  return {
    title: `Blog - ${blog.title}`,
    description: "Generated by create next app",
  };
}

export default async function BlogDetail({ params }: BlogDetailPageProps) {
  const { blogId } = params;

  const blog = await getData<BlogType>(`${ENDPOINTS.BLOGS}/${blogId}`);

  return (
    <>
      <PageTitle title={blog.title} />

      <section className="bg0 p-t-52 p-b-20">
        <div className="container">
          <div className="row">
            <div className="col-md-8 col-lg-9 p-b-80">
              <div className="p-r-45 p-r-0-lg">
                <div className="wrap-pic-w how-pos5-parent">
                  <img src={blog.img} alt="IMG-BLOG" />
                </div>

                <div className="p-t-32">
                  <span className="flex-w align-items-center flex-m stext-111 cl2 p-b-19">
                    <span className="flex-c-m mr-3 bor7 p-lr-15 trans-04">
                      {blog.category}
                    </span>

                    <span>
                      <span className="cl4">By</span> {blog.author}
                      <span className="cl12 m-l-4 m-r-6">|</span>
                    </span>

                    <span>{blog.date}</span>
                  </span>

                  <h4 className="ltext-109 cl2 p-b-28">{blog.title}</h4>

                  <p className="stext-117 cl6 p-b-26">{blog.first_content}</p>

                  <p className="stext-117 cl6 p-b-26">{blog.second_content}</p>
                </div>
              </div>
            </div>

            <div className="col-md-4 col-lg-3 p-b-80">
              <div className="side-menu">
                <RelatedBlogs />
              </div>
            </div>
          </div>
        </div>
      </section>
    </>
  );
}

export async function generateStaticParams() {
  const blogs = await getData<BlogType[]>(ENDPOINTS.BLOGS);

  return blogs.map((blog) => ({
    blogId: blog.id.toString(),
  }));
}
