"use client";

import ShopPageFilter from "@/components/ShopPageFilter";
import { ENDPOINTS } from "@/lib/endpoints";
import { ProductType } from "@/lib/types";
import { getData } from "@/lib/utils";
import Head from "next/head";
import Link from "next/link";
import { useSearchParams } from "next/navigation";
import { useEffect, useState } from "react";

export default function Shop() {
  const searchParams = useSearchParams();
  const q = searchParams.get("q");
  const gender = searchParams.get("gender_like");

  const [products, setProducts] = useState<ProductType[]>([]);

  useEffect(() => {
    async function fetchProducts() {
      const query = new URLSearchParams();
      if (q) query.set("q", q);
      if (gender) query.set("gender_like", gender);

      const data = await getData<ProductType[]>(
        `${ENDPOINTS.PRODUCTS}?${query.toString()}`
      );
      setProducts(data);
    }
    fetchProducts();
  }, [q, gender]);

  return (
    <>
      <Head>
        <title>Store</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <div className="bg0 m-t-23 p-b-140">
        <div className="container">
          <ShopPageFilter />

          <div className="row isotope-grid">
            {products.length === 0 && <p>No products found.</p>}
            {products.length > 0 &&
              products.map((product) => (
                <div
                  className="col-sm-6 col-md-4 col-lg-3 p-b-35 isotope-item women"
                  key={product.id}
                >
                  <div className="block2">
                    <div className="block2-pic hov-img0">
                      <img src={product.img} alt="IMG-PRODUCT" />

                      <Link
                        href={`/shop/${product.id}`}
                        className="block2-btn flex-c-m stext-103 cl2 size-102 bg0 bor2 hov-btn1 p-lr-15 trans-04 js-show-modal1"
                      >
                        View Details
                      </Link>
                    </div>

                    <div className="block2-txt flex-w flex-t p-t-14">
                      <div className="block2-txt-child1 flex-col-l ">
                        <a
                          href="product-detail.html"
                          className="stext-104 cl4 hov-cl1 trans-04 js-name-b2 p-b-6"
                        >
                          {product.title}
                        </a>

                        <span className="stext-105 cl3">{product.price}</span>
                      </div>
                    </div>
                  </div>
                </div>
              ))}
          </div>

          <div className="flex-l-m flex-w w-full p-t-10 m-lr--7">
            <a
              href="#"
              className="flex-c-m how-pagination1 trans-04 m-all-7 active-pagination1"
            >
              1
            </a>

            <a href="#" className="flex-c-m how-pagination1 trans-04 m-all-7">
              2
            </a>

            <a href="#" className="flex-c-m how-pagination1 trans-04 m-all-7">
              3
            </a>
          </div>
        </div>
      </div>
    </>
  );
}
