import type { Metadata } from "next";
import React from "react";
import BlogItem from "../../components/BlogItem";
import PageTitle from "../../components/PageTitle";
import { ENDPOINTS } from "@/lib/endpoints";
import { BlogType } from "@/lib/types";
import { getData } from "@/lib/utils";
import BlogFilter from "@/components/BlogFilter";

export const metadata: Metadata = {
  title: "Store - Blog",
  description: "Generated by create next app",
};

export default async function Blog({
  searchParams,
}: {
  searchParams: { q?: string; category?: string };
}) {
  const allBlogs = await getData<BlogType[]>(ENDPOINTS.BLOGS);
  const categories = Array.from(new Set(allBlogs.map((blog) => blog.category)));

  const query = new URLSearchParams();

  if (searchParams.q) query.append("q", searchParams.q.toLowerCase());
  if (searchParams.category) query.append("category", searchParams.category);

  const blogs = await getData<BlogType[]>(
    `${ENDPOINTS.BLOGS}?${query.toString()}`
  );

  return (
    <>
      <PageTitle title="Blog" />

      <section className="bg0 p-t-62 p-b-60">
        <div className="container">
          <div className="row">
            <div className="col-md-8 col-lg-9 p-b-80">
              <div className="p-r-45 p-r-0-lg">
                {/* blog item */}
                {blogs.length === 0 && (
                  <p>There are no results with your search.</p>
                )}

                {blogs.length > 0 &&
                  blogs.map((blog) => <BlogItem key={blog.id} {...blog} />)}
              </div>
            </div>

            <BlogFilter categories={categories} />
          </div>
        </div>
      </section>
    </>
  );
}
