import BlogItem from "@/components/BlogItem";
import PageTitle from "@/components/PageTitle";
import ProductItem from "@/components/ProductItem";
import { ENDPOINTS } from "@/lib/endpoints";
import { BlogType, ProductType } from "@/lib/types";
import { getData } from "@/lib/utils";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Challenge 24 - Next JS E-commerce",
  description: "Generated by create next app",
};

export default async function Search({
  searchParams,
}: {
  searchParams: { q?: string };
}) {
  const query = new URLSearchParams();
  if (searchParams.q) query.append("q", searchParams.q.toLowerCase());

  const blogs = await getData<BlogType[]>(
    `${ENDPOINTS.BLOGS}?${query.toString()}`
  );

  const products = await getData<ProductType[]>(
    `${ENDPOINTS.PRODUCTS}?${query.toString()}`
  );

  return (
    <>
      <PageTitle title="Search" />

      <div className="bg0 m-t-23 p-b-140 mt-5">
        <div className="container">
          <>
            {blogs.length === 0 && products.length === 0 && (
              <p>No results found</p>
            )}

            {blogs.length > 0 && (
              <>
                <h2 className="mb-5">Blogs</h2>
                <div className="row isotope-grid">
                  {blogs.map((blog) => (
                    <div className="col-4" key={blog.id}>
                      <BlogItem {...blog} />
                    </div>
                  ))}
                </div>
              </>
            )}
          </>

          <>
            {products.length > 0 && (
              <>
                <h2 className="mb-5">Products</h2>
                <div className="row isotope-grid">
                  {products.map((product) => (
                    <div className="col-4" key={product.id}>
                      <ProductItem {...product} />
                    </div>
                  ))}
                </div>
              </>
            )}
          </>
        </div>
      </div>
    </>
  );
}
